### Importing Libraries

In [9]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm
from sklearn import datasets

### Dataset
- Here we used an iris dataset. The size of the dataset is $150\times4$. The data was importedd from sklearn dataset where the data was stored as a dictionary with multiple keys. like -['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module].
- Here for implementation, we used only two keys: ' data' and  'target'. Where the dimension of data is $150\times 4$ and target dimension is $150\times1$. The target array has three classes for prediction.
- Then we shuffle both data and target maining their order. After that we split the data into two parts: training data with dimension $100\times4$ and test data with dimension $50\times4$.

In [11]:
iris = datasets.load_iris()

In [12]:
type(iris)

sklearn.utils._bunch.Bunch

In [13]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [18]:
data=iris["data"]

In [20]:
target=iris["target"]

In [22]:
data.shape

(150, 4)

In [24]:
type(data)

numpy.ndarray

In [26]:
data[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [28]:
target.shape

(150,)

In [30]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [32]:
np.random.seed(42)
shuffle=np.random.permutation(150)
data=data[shuffle]
target=target[shuffle]

In [34]:
data[:10]

array([[6.1, 2.8, 4.7, 1.2],
       [5.7, 3.8, 1.7, 0.3],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.9, 4.5, 1.5],
       [6.8, 2.8, 4.8, 1.4],
       [5.4, 3.4, 1.5, 0.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.9, 3.1, 5.1, 2.3],
       [6.2, 2.2, 4.5, 1.5],
       [5.8, 2.7, 3.9, 1.2]])

In [36]:
target

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2, 1, 2, 1, 0, 2, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0,
       1, 2, 0, 1, 2, 0, 2, 2, 1, 1, 2, 1, 0, 1, 2, 0, 0, 1, 1, 0, 2, 0,
       0, 1, 1, 2, 1, 2, 2, 1, 0, 0, 2, 2, 0, 0, 0, 1, 2, 0, 2, 2, 0, 1,
       1, 2, 1, 2, 0, 2, 1, 2, 1, 1, 1, 0, 1, 1, 0, 1, 2, 2, 0, 1, 2, 2,
       0, 2, 0, 1, 2, 2, 1, 2, 1, 1, 2, 2, 0, 1, 2, 0, 1, 2])

In [38]:
data_train=data[:100]

In [40]:
data_train.shape

(100, 4)

In [42]:
data_test=data[100:]

In [44]:
data_test.shape

(50, 4)

In [46]:
target_train=target[:100]

In [48]:
target_test=target[100:]

### Kernel Density Function
At this point we designed our kernel function. We used multidimensional gaussian like $4$-dimensional Gaussian Kernel function which is expressed mathematically as: 
$$
K(x) = {2\pi}^{-\frac{d}{2}} {det(H)}^{-\frac{1}{2}} e^{-\frac{1}{2} {x^T} {H^{-1}}x}
$$
where $d$ can be a size of train data, column in multi-dimensional case and $H$ is an identitiy mstrix of dimension $4$. We calculate the Kernel density at some point $x$ using the formula:
$$
f(x) = {\frac{1}{n}}{\sum_{i=1}^{n}K(x-x_{i})}
$$
Where $x_{i}$ denotes the $i$-th data point of the training data which is used to calculate the density at point any point $x$. We can put each test data as an argument to this function to obtain densities at the test data points. Note that in the multi-dimensional case $x$ and $x_i$ are both vectors of dimension $4$. In general if we are dealing with an $n$-dimentional data, then $x$ and $x_i$ would be vectors of dimnesion $n$ and the bandwidth or covariance matrix $H$ has to be of dimension $n\times n$.

In [8]:
def k(H, x, d):
    H_inv=np.linalg.inv(H)
    xt=np.matrix.transpose(x)
    y_1=np.matmul(xt,H_inv)
    y=np.matmul(y_1,x)
    exponent=np.exp(-0.5*y)
    t_1=1/np.sqrt(np.linalg.det(H))
    t_2=(2*np.pi)**(-d/2)
    t=t_1*t_2*exponent
    return t

In [314]:
def density_gen(data_test, data_train):
    density_list=[]
    for j in range(len(data_test)):
        s=0
        for i in range(len(data_train)):
            xi=data_train[i]
            dif=data_test[j]-xi 
            s=s+k(np.identity(data_train.shape[1]), dif, data_train.shape[1])
        density_list.append(s/len(data_train))
    return np.array(density_list)

In [316]:
density_list=density_gen(data_test,data_train)

In [318]:
density_list.shape

(50,)

### Classification
 - We have three target values in our data. We partitioned our training data as per these target values or classes.
 - We used the three class-wise partitions of the training data to claculate three separate density distribitions for each test data point.
 - For each test data point we identify the density distribution of the target class for which that test data point exhibits maximum density value.
 - The identified target class is predicted as the target of that test data point
 - We than compare the predicted taget value with the original target values to observe that our model produces an accuracy of $92$ percent.

In [320]:
def get_class_data(class_index,data,target):
    class_data=[]
    for i in range(len(target)):
        if target[i]==class_index:
            class_data.append(data[i])
    return np.array(class_data)

In [322]:
class0_data_train=get_class_data(0,data_train,target_train)

In [324]:
class1_data_train=get_class_data(1,data_train,target_train)

In [326]:
class2_data_train=get_class_data(2,data_train,target_train)

In [301]:
class_0_density_list=density_gen(data_test,class0_data_train)

In [303]:
class_1_density_list=density_gen(data_test,class1_data_train)

In [305]:
class_2_density_list=density_gen(data_test,class2_data_train)

In [359]:
class_0_density_list[25]

0.0003690785932502478

In [361]:
class_1_density_list[25]

0.017838473830496422

In [363]:
class_2_density_list[25]

0.005764137208793522

In [365]:
target_test[25]

1

In [373]:
predicted_classes=[]
for i in range(len(data_test)):
    predicted_class=np.argmax(np.array([class_0_density_list[i],class_1_density_list[i],class_2_density_list[i]]))
    predicted_classes.append(predicted_class)

In [385]:
np.sum(np.array(predicted_classes)==target_test)/len(target_test)

0.92